/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LoteDeCarros;
import DataManager.*;
import DataManager.Pool.*;


public class App {
    public static void main(String[] args) {
        try{
            //Demostracion altas
            Brand marca = new Brand();
            marca.setBrandName("BMW");
            BrandPool.get().registerComponent(marca);
            
            Model modeloSport = new Model(marca);
            modeloSport.setModelName("300-I");
            ModelPool.get().registerComponent(modeloSport);

            Model modeloCasual = new Model(marca);
            modeloCasual .setModelName("X5");
            ModelPool.get().registerComponent(modeloCasual);

            Vehicle carro1 = new Vehicle(modeloCasual);
            VehiclePool.get().registerComponent(carro1);

            System.out.println("Elementos totales(Alta): " + BrandPool.get().getComponentAt(0).countChildrenRecurively());

            //Demostracion Cambios
            System.out.println("Nombre del modelo de carro antes de actualizar: " + carro1.getModel().getModelName());
            Model modeloSus = new Model(null);
            modeloSus.setModelName("AmongusCar");
            ModelPool.get().updateComponent(modeloCasual, modeloSus);
            System.out.println("Nombre del modelo de carro despues de actualizar: " + carro1.getModel().getModelName());
            System.out.println("Elementos totales(Cambios): " + BrandPool.get().getComponentAt(0).countChildrenRecurively());
            
            //Demostracion Bajas Individuales: Eliminar el modelo "Sport"(sin hijos)
            ModelPool.get().unregisterComponent(modeloSport);
            System.out.println("Elementos totales(Baja Individual): " + BrandPool.get().getComponentAt(0).countChildrenRecurively());

            //Demostracion Bajas en cascada: Buscar marca con nombre "BMW" y borrarla
            for(int i = 0; i < BrandPool.get().countRegisterdComponents(); i++){
                var currentBrand = (Brand)BrandPool.get().getComponentAt(i);
                if(currentBrand.getBrandName().equals("BMW")) {
                    BrandPool.get().unregisterComponent(currentBrand);
                }
            }
            System.out.println("Elementos en piscina de datos despues de baja en cascada");
            System.out.println("Cantidad de elementos en BrandPool: " + BrandPool.get().countRegisterdComponents());
            System.out.println("Cantidad de elementos en ModelPool: " + ModelPool.get().countRegisterdComponents());
            System.out.println("Cantidad de elementos en VehiclePool: " + VehiclePool.get().countRegisterdComponents());

        }catch(ComponentNotBoundToPool ex){
            System.out.println("Error: " + ex.getMessage());
        }
    }
}
